clearcontainers/runtime

- .ci/go-test.sh
- .travis.yml
- Makefile
- README.md
> travis: Enable code coverage with coveralls

- .travis.yml
> ci: Send travis notifications to slack

- config.go
- create.go
- delete.go
- kill.go
- oci.go
- shim.go
- start.go
- state.go
This PR implements the create function relying on OCI runtime specification.
> Implement OCI runtime specification

- .travis.yml
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
> travis: Add go 1.8 to the test matrix

- config.go
- create.go
- exec.go
- shim.go
This PR adds a first implementation of the exec command.
> exec: Implement OCI CLI spec for exec

- create.go
- delete.go
- oci.go
In config.json, a cgroupsPath is provided, and it is expected to be
created. "tasks" and "cgroup.procs" have to be created under this
directory, and filled with the shim's pid. That way, nothing else
will try to create those files on our behalf.
Because we know where we created the files, we are able to remove
them when delete() is called. By removing those files, we make sure
to prevent any file descriptor leak.
> cgroups: Create and delete cgroups files related to provided path

- .travis.yml
- config.go
- config_test.go
- create_test.go
- delete_test.go
- main_test.go
- oci_test.go
- shim/mock/shim.go
- shim_test.go
Unit testing was very limited for this project. This PR aims to fix that by providing a lot of unit tests for each source file, increasing the project coverage.
> Improve unit testing coverage

- config.go
- config/configuration.toml
- config_test.go
- create.go
- create_test.go
- delete.go
- delete_test.go
- oci.go
- oci_test.go
- shim.go
Here we have a list of patches aiming to fix the runtime so that it can properly work with shim/proxy 3.0.
> Fix runtime due to shim/proxy 3.0 enabling

- config.go
- create.go
- delete.go
- main.go
- shim.go
This PR first fixes a mistake coming from a previous one. Then it makes the runtime more consistent by using logrus everywhere, instead of glog.
> Fix runtime and improve logger

- main.go
Each time the runtime is called, log version details and arguments to
the logfile.
> logging: Add details of runtime to logfile.

- lock.json
- manifest.json
- vendor/github.com/containers/virtcontainers/NEWS
- vendor/github.com/containers/virtcontainers/api.go
- vendor/github.com/containers/virtcontainers/api_test.go
- vendor/github.com/containers/virtcontainers/container.go
- vendor/github.com/containers/virtcontainers/pod.go
- vendor/github.com/containers/virtcontainers/qemu.go
- vendor/github.com/containers/virtcontainers/qemu_test.go
- vendor/github.com/containers/virtcontainers/sshd.go
This PR updates virtcontainers vendoring to version 0.7.0.
> vendor: Update virtcontainers vendoring to 0.7.0 version

- CONTRIBUTING.md
This is copied from virtcontainers.
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
> CONTRIBUTING: Add a contributing document

- .pullapprove.yml
- CONTRIBUTING.md
- OWNERS
> OWNERS: Add OWNERS file

- main.go
- run.go
- start.go
Run command implementation
fixes #94
> Run command

- run.go
> run: delete container's resources once container ends

- list_test.go
Historically, it has been possible to marshal and demarshal a time.Time and
compare the original and demarshaled values for equality (successfully).
However, go tip (what will presumably become go1.9) changes this behaviour. It
introduces a monotonic element to the time.Time internal representation. Thie
monotonic value (shown as "m=±ddd.nnnnnnnnn" when calling String() on the
time.Time object) is *NOT* retained when marshaling a time.Time.
This ensures comparing the unmarshaled value with the original will fail.
The fix is to call Truncate(0) on the original time.Time object to remove the
monotonic element before attempting comparing with the unmarshaled value.
This change corrects the required "fixup" behaviour in TestStateToJSON() to be
in line with golang expectations.
See: …
> tests: Fix JSON list format tests for go1.9+.

- Makefile
Nothing too drastic. Just make sure people can use PREFIX as usual (or almost, we don't have an autogen/configure pass),
> a couple of Makefile tweaks

- config_test.go
Add basic tests for checkConfigParams().
> tests: Add unit test for checkConfigParams().

- docs/developers-clear-containers-install.md
A Quick Start guide to start using and testing Clear Containers 3.0
Signed-off-by: Geronimo Orozco <geronimo.orozco@intel.com>
> docs: Add developers install guide

- cc-check.go
- cc-env.go
- cc-env_test.go
- config.go
- config_test.go
- main.go
- utils.go
- utils_test.go
Introduce a new "cc-env" command that displays configuration details.
Fixes #228.
> cli: Add "cc-env" command

- docs/developers-clear-containers-install.md
Add a note explaining that "make help" can be used to obtain further
information on the build system.
> docs: Mention "make help" in developer doc.

- .ci/run.sh
Produce less output by default for some of the CI tests.
> CI: Quieten CI output.

- logger_test.go
Added missing test cases to ensure full logger unit test coverage.
> tests: Increase logger test coverage to 100%.

- cc-check.go
- cc-check_test.go
> tests: Increase unit test coverage for cc-check.go

- Gopkg.lock
- create.go
- vendor/github.com/containers/virtcontainers/NEWS
- vendor/github.com/containers/virtcontainers/README.md
- vendor/github.com/containers/virtcontainers/agent.go
- vendor/github.com/containers/virtcontainers/capabilities.go
- vendor/github.com/containers/virtcontainers/capabilities_test.go
- vendor/github.com/containers/virtcontainers/container.go
- vendor/github.com/containers/virtcontainers/hyperstart.go
- vendor/github.com/containers/virtcontainers/hypervisor.go
- vendor/github.com/containers/virtcontainers/hypervisor_test.go
- vendor/github.com/containers/virtcontainers/mount.go
- vendor/github.com/containers/virtcontainers/mount_test.go
- vendor/github.com/containers/virtcontainers/noop_agent.go
- vendor/github.com/containers/virtcontainers/pkg/hyperstart/types.go
- vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
- vendor/github.com/containers/virtcontainers/pkg/oci/utils_test.go
- vendor/github.com/containers/virtcontainers/pod.go
- vendor/github.com/containers/virtcontainers/pod_test.go
- vendor/github.com/containers/virtcontainers/qemu.go
- vendor/github.com/containers/virtcontainers/qemu_test.go
- vendor/github.com/containers/virtcontainers/sshd.go
- vendor/github.com/containers/virtcontainers/utils.go
- vendor/github.com/containers/virtcontainers/utils_test.go
This PR first vendor virtcontainers.
Then it includes the ability to add some kernel parameters to the kernel command line executed by the hypervisor, we have to add Clear Containers specific parameters from the runtime implementation.
> Vendor virtcontainers and configure Clear Containers specific kernel parameters

- docs/developers-clear-containers-install.md
Fix outdated links and add some info on installation of qemu-lite,
rootfs and kernel images.
Signed-off-by: Dmitry Voytik <dmitry.voytik@huawei.com>
> docs: update developers-clear-containers-install.md

- Makefile
Regenerate config-generated.go if Makefile and/or VERSION files
changed.
Fixes #302.
Signed-off-by: Dmitry Voytik <dmitry.voytik@huawei.com>
> build: regenerate config-generated.go

- docs/developers-clear-containers-install.md
- docs/fedora-installation-guide.md
- docs/ubuntu-installation-guide.md
runtime name: clearcontainers
config-files: clear-containers
repo: http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/
Fixes: #319
Signed-off-by: Geronimo Orozco <geronimo.orozco@intel.com>
> docs: Consistency on dev/user documentation

- exec.go
This patch implements the detach option for the exec command. In case
the flag is set to false, we stay attached to the process. This means
we have to wait for the end of the shim process and return the exit
code through the runtime itself.
Docker already implements this option on his own, meaning this patch
is useful for cases where the runtime is used as a standalone binary.
For instance, CRI-O uses the runtime with this option, meaning it
expects this to work as expected.
Fixes #318
> exec: Implement detach option

- .ci/go-static-checks.sh
Minor fixes to the go-static-checks script
Fixes: #306
> ci: minor go-static-checks fixes

- CONTRIBUTING.md
Add mailing list and irc details to "CONTRIBUTING.md".
Fixes #364.
> doc: Add contact section to CONTRIBUTING.md

- docs/developers-clear-containers-install.md
- docs/fedora-installation-guide.md
- docs/ubuntu-installation-guide.md
Simplified the developer installation instructions for the runtime
(possible since PR #288 has landed).
Fixes #367.
> docs: Simplify runtime build instructions

- README.md
- docs/limitations.md
Add a document listing the known limitations.
Fixes #338.
> docs: Document limitations.

- Makefile
Install git hooks which handle cases when git HEAD is changed.
The git hooks just remove config-generated.go file to force
binary rebuild.
Fixes #431.
Signed-off-by: Dmitry Voytik <dmitry.voytik@huawei.com>
> build: rebuild if git HEAD changed

- oci_test.go
this patch adds the unit test for isCgroupMounted function
Fixes #405
>  test: add unit test for isCgroupMounted function

- console_test.go
this patch add unit tests for console Read and Write
methods increasing the code coverage
fixes #406
>  test: add unit test for console Read and Write

- main_test.go
Rather than relying on the pause bundle, use a known good docker image
to create an OCI bundle from.
Also, added some tests for the OCI test functions.
Fixes #458.
> tests: Rework OCI helper functions

- delete_test.go
This should increase the test coverage
Fixes #400
> tests: Add tests for delete using mock framework

- run_test.go
this patch increase the coverage of run.go
fixes #397
> tests: add unit tests for run.go

- kill_test.go
- main_test.go
Relying on vcMock framework introduced in virtcontainers library,
this commit raises the unit test coverage of kill.go file to 100%.
Fixes #403
> kill: Implement full unit test coverage

- state_test.go
increase code coverage of state.go
fixes #395
> tests: add unit tests for state.go

- oci_test.go
Add new tests to increase unit-test coverage on "oci.go".
Fixes #477.
> tests: Increase oci.go unit-test coverage

- .ci/run.sh
- .ci/setup.sh
This commit slightly improves CI scripts so that they work both for
Semaphore and our future Jenkins CI.
Fixes #481
>  .ci: Fix runtime CI scripts to work with Jenkins

- .ci/go-test.sh
Don't run the unit-tests twice if the user that invokes the tests is
already root since both runs would be running as `root`.
Also, ensure the HTML report generated by test_html_coverage() is
readable by all users.
Fixes #496.
> tests: Only re-run unit-tests if not initially running as root

- console.go
- console_test.go
> tests: increase code coverage in console.go

- run_test.go
this patch increase run.go code coerage to 92.3%
fixes #498
> tests: increase run.go code coverage

- Gopkg.lock
- vendor/github.com/01org/ciao/packages.json
- vendor/github.com/01org/ciao/qemu/qemu.go
- vendor/github.com/01org/ciao/qemu/qemu_test.go
- vendor/github.com/01org/ciao/ssntp/README.md
- vendor/github.com/01org/ciao/ssntp/ssntp.go
- vendor/github.com/containers/virtcontainers/Gopkg.lock
From ciao/qemu we need:
f12f43d Knobs: Modify the behaviour of the Mlock knob.
to fix #568
Fixes #579
> vendor: Pull latest virtcontainers and ciao/qemu changes

- CONTRIBUTING.md
- Makefile
- data/cc-collect-data.sh
Provide a script that users can run to help developers diagnose
problems.
Fixes #591.
> scripts: Create script to gather environment details

- docs/developers-clear-containers-install.md
> docs: developers: how to build custom kernel

- Gopkg.lock
- create_test.go
- main_test.go
- run_test.go
- vendor/github.com/stretchr/testify/.travis.yml
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/assert/assertions_test.go
- vendor/github.com/stretchr/testify/assert/forward_assertions.go
- vendor/github.com/stretchr/testify/assert/http_assertions.go
- vendor/github.com/stretchr/testify/assert/http_assertions_test.go
revendor testify
go vet: Fix issues detected by go vet in go 1.9
Fixes https://github.com/clearcontainers/runtime/issues/586
> Fix go vet issues flagged by go 1.9

- .gitignore
- Makefile
- data/cc-collect-data.sh.in
Various improvements to `cc-collect-data.sh` script including:
- Display of script version number (script is now generated by build).
- Improved formatting.
- More patterns to try harder looking for problems in the global log.
- punctuation in output (!)
- Addition of sub-sections to break up the output in a more logical fashion.
> Improve collect data script

- ISSUE_TEMPLATE.md
Add a "magic" github file that will be used to pre-populate the text
box for:
https://github.com/01org/cc-oci-runtime/issues/new
Fixes #589.
> process: Add github issue template

- list.go
- list_test.go
If a container was using old assets (kernel + image) and those assets
were then updated, "list --cc-all" would show, incorrectly, that the
existing container was using the latest asset versions, not the correct
older versions.
Removed a couple of now-incorrect tests and added a new one to assert
the correct list behaviour.
Fixes #628.
> list: Ensure "--cc-all" details are correct

- docs/debug-kernel.md
Add details on how to obtain the VM Kernel boot logs
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> Docs: Add documentation for obtaining VM Kernel logs

- cc-check.go
- cc-check_test.go
- config.go
- create.go
- create_test.go
- delete.go
- delete_test.go
- logger.go
- logger_test.go
- main.go
- main_test.go
- oci.go
Use structured or context logging for more useful log messages.
Fixes #633.
> logging: Switch to structured logging

- docs/clearlinux-installation-guide.md
This commit documents the steps needed to setup Clear Containers
3.0 in Clear Linux.
Fixes #601.
> docs: Add Clear Linux installation guide.

- list.go
- list_test.go
Add three new columns to the "list --cc-all" output:
- LATEST-KERNEL (Newest locally-available kernel)
- LATEST-IMAGE  (Newest locally-available image)
- STALE         (String describing if the current kernel or image are not current).
Fixes #630.
> list: Add columns to extended output to show stale assets

- versions.txt
- Agent: new structured log.
Fixes: #694
> versions: update image to 18220

- oci.go
- oci_test.go
Starting 2 containers with the same ID prefixes is a valid use case.
Docker CLI supports shortened container IDs but always call the runtime
with the full and complete ID.
Fixes #699
> oci: Support containers with identical ID prefixes

- Gopkg.lock
- cc-check_test.go
- create_test.go
- main_test.go
- run_test.go
- vendor/github.com/stretchr/testify/.travis.yml
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/assert/assertions_test.go
- vendor/github.com/stretchr/testify/assert/forward_assertions.go
- vendor/github.com/stretchr/testify/assert/http_assertions.go
- vendor/github.com/stretchr/testify/assert/http_assertions_test.go
Fix go vet errors detected by go ver 1.9
> go 1.9 go vet fixes

- oci.go
- oci_test.go
get cgroup directory path from mountinfo instead of
using /sys/fs/cgroup/, since maybe not all os use that path.
Fixes 719.
Signed-off-by: Ace Tang <aceapril@126.com>
> oci: do not use specified cgroup dir path

- versions.txt
- Update kernel
- Update image
- Update last supported docker
Fixes: #728
> versions: Update artefacts and supported versions.

- docs/ubuntu-installation-guide.md
This will update the installation guide for ubuntu 16.10 and 17.04
Fixes #732
> Docs: Update Installation Guide for Ubuntu

- docs/fedora-installation-guide.md
This installation guide supports Fedora 26.
Fixes #731
> Docs: Update installation guide for Fedora

- versions.txt
Update versions to last kernel and image packages.
Fixes: #761
> versions: Update assets versions

- cc-check.go
- cc-check_test.go
- cc-env_test.go
- config.go
- delete_test.go
- run_test.go
- start_test.go
- utils.go
- utils_test.go
tests: Increase unit test coverage
Add new tests to improve the overall unit-test coverage.
Fixes #759.
> Unit test coverage fixes

- docs/architecture/architecture.md
We describe the relationship between CRI-O and CC, and how they
work together to properly support VM based runtimes for Kubernetes.
Fixes #726
> docs: Add Kubernetes section to the architecture document

- docs/assets-update.md
Describe how are updated:
linux-container for the kernel
clear-containers-image for the rootfs image
Fixes: #632
> docs: Document how and when we update the assets

- docs/fedora-installation-guide.md
- docs/ubuntu-installation-guide.md
Make the Ubuntu and Fedora installation documents as similar as
possible by ensuring consistent wording, formating and behaviour.
Fixes #752.
> docs: Install doc fixes

- cc-check.go
If running as `root`, determine if it is possible to create a new
virtual machine. Special-case the scenario where another hypervisor
is running and explain the problem to the user.
Fixes #848.
> cc-check: Add extra checks

- docs/bclinux-installation-guide.md
- docs/centos-installation-guide.md
- installation/centos-setup.sh
Add a new script of bclinux-setup.sh to add support to the [BC-Linux](https://www.bclinux.org/) system.
Signed-off-by: tangzhongrui tangzhongrui@cmss.chinamobile.com
> Add support to BC-Linux system

- docs/ubuntu-installation-guide.md
This will update the documentation for Ubuntu 17.10
Fixes #881
> docs: Update install documentation for Ubuntu

- docs/limitations.md
doc: limitations: fix typo (repeated word)
Fixes #915 .
Signed-off-by: William Zhang <warmchang@outlook.com>
> doc: limitations: fix typo (repeated word)

- versions.txt
Change to last known working version.
Fixes: #922
> Versions: update last working agent

- docs/rhel-installation-guide.md
- installation/rhel-setup.sh
- versions.txt
This will install cc-runtime on RHEL.
Fixes #463
> installation: RHEL installation script for cc-runtime.

- Makefile
- data/collect-data.sh.in
Update the collect script for Kata Containers (previously, it still
hard-coded Clear Containers specifics, which caused it to fail).
Fixes #965.
> scripts: Update collect script for Kata

- versions.txt
Latest agent version fixes issues with exec wrong output.
Fixes: #997
> versions: Update agent version

- arch/arm64-options.mk
This will add the support for ARM architecture.
Fixes #1008
> build: Add architecture framework for ARM

- installation/rhel-setup.sh
With this instead of using Docker-EE, we are retrieving Docker
from the server repositories.
Fixes #1016
> installation: Update RHEL installation script

- docs/architecture/architecture.md
- docs/limitations.md
Fix some spelling mistakes in the docs.
Fixes #1062.
> docs: Fix typos
