clearcontainers/runtime

lock.json
manifest.json
vendor/github.com/containers/virtcontainers/api.go
vendor/github.com/containers/virtcontainers/api_test.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/hyperstart.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/pod_test.go

In order to implement the OCI runtime relying on virtcontainers, we need
to rely on latest changes:
- Pod and containers state are now public to perform the translation to
OCI specific states.
- PID and RootFs stored inside the Pod object are copied to the PodStatus,
making those info available from "state" command using StatusPod() API.

vendor: virtcontainers vendoring update

---

kill.go
oci.go
state.go

The runtime implementation has to check if the process running inside the
container is still running. In case it is not running anymore, we want to
call StopContainer API from virtcontainers so that it removes the container
from the pod, and it gets the container status updated.

Update container's state if stopped

---

create.go
delete.go
kill.go
start.go
state.go

The way to get arguments from the CLI was not functional. This patch
fixes it for create, delete, kill, start and state actions.

cli: Fix arguments retrieval from CLI

---

config.go
config_test.go
lock.json
manifest.json
vendor/github.com/containers/virtcontainers/agent.go
vendor/github.com/containers/virtcontainers/api.go
vendor/github.com/containers/virtcontainers/api_test.go
vendor/github.com/containers/virtcontainers/cc_proxy.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/hyperstart.go
vendor/github.com/containers/virtcontainers/noop_agent.go
vendor/github.com/containers/virtcontainers/noop_agent_test.go
vendor/github.com/containers/virtcontainers/noop_proxy.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/proxy.go
vendor/github.com/containers/virtcontainers/sshd.go

This PR updates virtcontainers vendoring for following reasons:
- EnterContainer() now returns a Pod pointer.
- Pod has a new public method URL() returning the proxy URL specific to the pod.
- CCProxyConfig contains now only one field: URL.
Then it fixes the build which is broken by this new vendoring.

Update virtcontainers vendoring

---

config.go
config_test.go

Proxy config now relies only on a URL provided to the library so
that it can connect to the proxy.

config: Update proxy config according to virtcontainers

---

config.go
config_test.go
create.go
exec.go
shim.go

We don't want the shim binary path to be hardcoded into the code.
That's why we rely on the configuration file to provide this data.

config: Retrieve shim path from configuration

---

create.go
lock.json
manifest.json
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils_test.go
vendor/github.com/containers/virtcontainers/pod.go

Need latest changes from virtcontainers:
- New "Annotations" field in PodConfig to store user specific data.
- OCI package update relying on this new Annotations field and providing new function to retrieve these annotations.
- OCI package returning OCI spec structure from PodConfig().
Fix build after the new vendoring.

vendor: Update virtcontainers vendoring and fix the build

---

lock.json
manifest.json
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/syscall.go

Fix virtcontainers vendoring because it was based on an old commit
version instead of the most recent one.

vendor: Update virtcontainers vendoring

---

create.go

When calling createCgroupsFiles(), we were expecting files to be
created with a call to os.OpenFile() but we forgot to specify the
right flag O_CREATE to make sure the file is created in case it
does not exist.

create: Add missing O_CREATE flag to OpenFile()

---

shim.go

The use of exec.cmd was not proper, causing the binary to be
re-executed. Relying on the exec.Command() function allows to
start cc-shim without re-executing it.

shim: Fix execution of cc-shim binary

---

.ci/go-static-checks.sh

We run gofmt with the simplify (-s) option. Some of the rewrite rules are
hidden behind that flag because they break previous go versions. Editors
don't run gofmt with -s by default for that reason and so it's not
unlikely the static checks scripts find something to change.
We can do better than displaying the list of "offending" files, we can
make gofmt display the unified diff with the suggested simplification.
It's just a matter of using the -d flag.
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>

ci: Display unified diff with what gofmt wants us to change

---

main.go

Set logfile mode to 0640 rather than 0666 for safety.

logging: Disable logfile access for "other".

---

exec.go
lock.json
manifest.json
vendor/github.com/containers/virtcontainers/agent.go
vendor/github.com/containers/virtcontainers/api.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/errors.go
vendor/github.com/containers/virtcontainers/filesystem.go
vendor/github.com/containers/virtcontainers/hack/virtc/README.md
vendor/github.com/containers/virtcontainers/hack/virtc/main.go
vendor/github.com/containers/virtcontainers/hyperstart.go
vendor/github.com/containers/virtcontainers/noop_agent.go
vendor/github.com/containers/virtcontainers/noop_agent_test.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils_test.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/qemu.go
vendor/github.com/containers/virtcontainers/qemu_test.go
vendor/github.com/containers/virtcontainers/sshd.go

Instead of using the console related to the container, a new process run on an existing container can have its own console.

Allow exec command to specify a different console

---

exec.go
kill.go

The "exec" and "kill" sub-commands both erroneously referenced "runc".

help: Remove references to "runc" in usage.

---

exec.go

The unmarshalling was failing because we were not passing a pointer to a specs.Process structure.
With this patch, the exec command works as expected.

exec: Unmarshal to a specs.Process pointer

---

.travis.yml

Because some permissions were missing, goveralls binary was not installed and we lost the coverage report.

ci: Fix coverage report with travis CI

---

.ci/install_virtcontainers.sh
.ci/upstart-services/cc-proxy.conf
config.go
config/configuration.toml
main.go

It has been decided that clear-containers will be cleaner and because we want to be consistent accross all projects, let's replace the name "clearcontainers" with "clear-containers".

runtime: Replace "clearcontainers" with "clear-containers" naming

---

kill.go
kill_test.go

With this commit kill command is able to handle numeric
signals as argument

kill: adds support for numeric signals

---

config/configuration.toml

The shim installation path is changed to
/usr/libexec/clear-containers. Change the config to reflect this.
Fixes #112

config: Change the configuration for shim path.

---

delete.go
exec.go
kill.go
oci.go
oci_test.go
start.go
state.go

Support the specification of partial container IDs. Now, the runtime
will expand a partial container ID as long as The container ID specified:
- is a valid container ID prefix.
- expands to a unique matching container ID.

cli: Allow partial container IDs.

---

main.go

Avoid attempting to load the configuration file when the help text
is displayed (when no arguments are specified or when the command is
specified as "help").
Previously, an error would be generated if the system either didn't
have a config file or it was not readable.

cli: Do not load config file when displaying help.

---

.pullapprove.yml
OWNERS

To prevent PRs from being blocked as PR pushers are also usually PR
approvers.

OWNERS: Add 2 additional owners

---

.ci/upstart-services/cc-proxy.conf

According to latest proxy changes, we cannot use glog flags anymore. Instead we have to call "./cc-proxy --log debug" if we want all debug traces to be provided by the proxy.

ci: Fix cc-proxy upstart service

---

Gopkg.lock
Gopkg.toml
create.go
oci.go
oci_test.go
vendor/github.com/containers/virtcontainers/.gitignore
vendor/github.com/containers/virtcontainers/.travis.yml
vendor/github.com/containers/virtcontainers/Gopkg.lock
vendor/github.com/containers/virtcontainers/Gopkg.toml
vendor/github.com/containers/virtcontainers/Makefile
vendor/github.com/containers/virtcontainers/api_test.go
vendor/github.com/containers/virtcontainers/cc_shim.go
vendor/github.com/containers/virtcontainers/cc_shim_test.go
vendor/github.com/containers/virtcontainers/hook_test.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/opencontainers/runtime-spec/README.md
vendor/github.com/opencontainers/runtime-spec/ROADMAP.md
vendor/github.com/opencontainers/runtime-spec/bundle.md
vendor/github.com/opencontainers/runtime-spec/config-linux.md
vendor/github.com/opencontainers/runtime-spec/config-solaris.md
vendor/github.com/opencontainers/runtime-spec/config.md
vendor/github.com/opencontainers/runtime-spec/glossary.md
vendor/github.com/opencontainers/runtime-spec/implementations.md
vendor/github.com/opencontainers/runtime-spec/project.md
vendor/github.com/opencontainers/runtime-spec/runtime-linux.md
vendor/github.com/opencontainers/runtime-spec/runtime.md
vendor/github.com/opencontainers/runtime-spec/spec.md
vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
vendor/github.com/opencontainers/runtime-spec/style.md

Rely on latest virtcontainers version introducing the new vendoring of runtime-spec v1.0.0-rc5. Virtcontainers also includes new structures for compatibility with runtime-spec structures changes between versions 1.0.0-rc4 and 1.0.0-rc5.
This patch also updates the current vendoring of the runtime to the version 1.0.0-rc5.

vendor: Update virtcontainers and runtime-spec vendoring

---

Makefile

The install target should handle installing a default
configuration file as well.
Ran into an issue where the dafaults changed within the code
but the the default configuration installed manually
pointed to old paths.

Makefile: Install default configuration

---

main.go

a configuration file could be specify through --config option
this option could be useful to run functional and integration tests

cli: add config option

---

main.go

If the user simply want to see a usage statement for a sub-command, the
config file should not be loaded.
Related to #137.

cli: Don't load config file when displaying help for sub-commands.

---

exec.go

With recent changes from virtcontainers, we have to rely on the compatible structures we have added so that we don't end up with unmarshalling errors regarding `LinuxCapabilities` field.

exec: Rely on oci.CompatOCIProcess instead of specs.Process

---

main.go
version.go

Added a new "version" command with the same output as "--version" for
parity with cc-oci-runtime and docker.

cli: Implement "version" command.

---

.ci/go-static-checks.sh

gofmt is run with the '-s' (simplify) option. This is not the default so
when this fails rather than simply returning a non-zero error code,
display the diff to give the user an indication of what went wrong.

CI: Be verbose when 'gofmt' fails.

---

.ci/go-test.sh

We're actually using the atomic counters when running our tests because
we run them with -race (2 lines later). We should set the mode of the
resulting coverage file to match this.
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>

tests: Produce a coverage file with atomic mode

---

.ci/go-test.sh
.gitignore
Makefile

Unfortunately, this is a bit awkward because one needs to be root to run the tests at the moment.
With an xhost + and run as root though, make coverage does open a browser with the coverage report.

HTML code coverage report

---

.ci/install_cc_runtime.sh
.ci/install_cc_tests.sh

This will install the cc-test repository as well as all the
dependencies for the functional tests.

ci: Add scripts to run cc tests

---

run.go

running in attach mode runtime should wait for the shim and
forward its exit code to the system
fixes #202

run: runtime should forward container exit code to the system

---

config_test.go

Add tests to ensure default and overriden values are correct for
hypervisor, proxy, shim and agent.

config: Add new tests for default values.

---

console.go
console_test.go
run.go

running containers under ginkgo or go test was causing issues
trying to duplicate stdio. with this patch stdio will be
duplicated only if stdio is a terminal
fixes #208

run: do not duplicate stdio if it is not a terminal

---

.ci/run.sh
.ci/setup.sh
.ci/teardown.sh

Currently, we hardcoded the commands that SemaphoreCI will
execute for building and testing the project, but any change
requires modification via its web page and we cannot track
any change there.
Therefore, these three scripts will be called in the SemaphoreCI
settings and any change should be done to the scripts instead
of changing the settings.
`setup.sh` will be called in the Setup
`run.sh` will be called on Job 1
`teardown.sh` will be called on After Job
fixes #168

Add CI scripts that SemaphoreCI will use in its project settings

---

create.go
create_test.go

runtime should not fail if pid file is missing since it
is optional
fixes #212

create: runtime should not fail if pid file is missing

---

.ci/run.sh
main.go
pause.go

Add two new commands: "pause" and "resume". The first suspends all
processes in a container, whilst the second "unpauses" or resumes a
container, allowing all processes within it to continue executing.
Fixes #99, #100.

cli: Implement pause and resume commands.

---

cc-check.go
cc-check_data_test.go
cc-check_test.go
main.go
utils.go
utils_test.go

This replaces the "clear-linux-check-config.sh" script by providing a
built-in way of determining if the host system is capable of running
Clear Containers.
Fixes #204.
Signed-off-by: Gabriel Briones Sayeg <gabriel.briones.sayeg@intel.com>

cli: Add "cc-check" command.

---

cc-check.go

It is better to define a const for this string since it's safer plus
it is placed near the top of the file for clarity.

cc-check: Make the "/proc/cpuinfo" string a const.

---

Makefile

Added a new "make help" target which shows:
- overview.
- available targets.
- variables that users may wish to override.
Also, display a summary for a normal build showing the final destination
for the runtime binary and the configuration file.

build: Make the build more friendly.

---

CONTRIBUTING.md

Ask the user to include the output of "cc-runtime cc-env" in their bug
reports to help identify and resolve the issue.

docs: Request users include "cc-env" output in issues.

---

list.go

Pods with more than 1 containers are not empty.
Fixes #248

list: Pods can contain more than one containers

---

kill.go

Regarding a recent update of the OCI specification, we don't want to generate an error when 'kill' command is called on a container which has been created but not started.
This is basically a no-op in our case.

kill: Don't return an error if container state is 'created'

---

.gitignore

We don't want to stage and commit those generated config files by mistake. Then let's add them to .gitignore file.

gitignore: Add generated config files to .gitignore

---

Gopkg.lock
Gopkg.toml
kill.go
vendor/github.com/containers/virtcontainers/api_test.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/pod_test.go

In case the container was created but not running, we were doing
nothing. This patch goes one step further by allowing the update
of the container state when the signal intends to terminate this
container, i.e SIGKILL or SIGTERM.

kill: Allow 'created' to 'stopped' state transition

---

docs/fedora-installation-guide.md
docs/ubuntu-installation-guide.md

This documentation guides you through the steps needed to run
Clear Containers 3.0 by installing the available packages from
OBS.
Fixes #241

docs: Add installation guides for Ubuntu and Fedora

---

utils_test.go

#253 inadvertently removed an os.Chdir test in TestRuntimeConfig() that
was exercising resolvePath().
Add a new test in the correct place to handle this scenario.

tests: Bring utils.go test coverage back to 100%.

---

version_test.go

Unit test coverage for version.go is now 100%.
Fixes #273.

tests: Add a unit test version.go

---

.ci/go-static-checks.sh
Makefile
docs/developers-clear-containers-install.md
pause/README.md
pause/pause.c

This commit adds the pause.c source file which provides
the "pause" binary.
- The build/install/clean rules were added to the top-level
Makefile.
- Instructions to the developers' documentation were modified.
- An exception to the ci static checks was added.
Fixes https://github.com/clearcontainers/runtime/issues/277

build: Add containers/virtcontainers pause binary

---

config.go

Rename the variables that deal with nested TOML tables and add a
comment explaining what they are for.
Fixes #284.

config: Give TOML table type variables better names.

---

docs/fedora-installation-guide.md
docs/ubuntu-installation-guide.md

The pause binary is now part of cc-runtime-bin.
Fixes #290

docs: No need to install the virtcontainers pause package

---

list.go

The list command currently provided a "--all" option, but it should be
called "--cc-all" for consistency with the other extensions.
Also, improve the description of the option and drop the "-a" short-form
(since short options cannot be made Clear Containers specific).
Fixes #295.

list: Rename option "--all" to "--cc-all".

---

.pullapprove.yml
OWNERS

Add @dlespiau and @grahamwhaley as additional project approvers.
Fixes #299.

CI: Add additional project approvers

---

.gitignore

pause/pause and pause/pause.o are generated files that we should
ignore.
Fixes #309

gitignore: Ignore generated files in the pause directory

---

.ci/go-test.sh

Because travis CI can be slow sometimes, the tests can be inconsistent
and fail after a 2 seconds timeout. In order to avoid those behaviors,
this patch increase the timeout from 2 to 5 seconds.
Fixes #312

.ci: Increase go test timeout to prevent from false negative tests

---

exec.go

runc expects the exec command to use the same options defined when
the container process was started. And if the command line provide
some options, we should override with what is provided.
Fixes #323

exec: Override container process option if needed

---

CONTRIBUTING.md

The CONTRIBUTING file did not have details of our Fixes
requirements for commits. Add some.
Fixes: #321

docs: Add Fixes: details to CONTRIBUTING file

---

.ci/go-static-checks.sh

This patch fix the find flag in go-static-checks.sh in order to
not include any file under ./pause/.
This was causing a warning when running the gofmt.
Fixes #313

.ci: Fix find flag in go-static-checks.sh

---

Makefile

Show details of `CC_SYSTEM_BUILD` variable in `make help` output.
Fixes #330.

build: Document CC_SYSTEM_BUILD.

---

Gopkg.lock
create.go
exec.go
oci.go
oci_test.go
run.go
vendor/github.com/containers/virtcontainers/.pullapprove.yml
vendor/github.com/containers/virtcontainers/Makefile
vendor/github.com/containers/virtcontainers/OWNERS
vendor/github.com/containers/virtcontainers/cc_shim.go
vendor/github.com/containers/virtcontainers/cc_shim_test.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/filesystem.go
vendor/github.com/containers/virtcontainers/hypervisor.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils_test.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/pod_test.go
vendor/github.com/containers/virtcontainers/shim.go

In case our runtime is used in standalone mode with the --detach
and tty flags enabled, we should not get any output on the current
shell. We should still be able to get some outputs if a console has
been provided though.
This patch relies on the latest virtcontainers vendoring to be
able to indicate if we are in case of a detached command or not.
Fixes #326

console: Don't link the shell to the shim if detach and tty are enabled

---

cc-env.go
cc-env_test.go

The purpose of this commit is to add some useful info related to the
hypervisor now that we have the machine type available.
EnvInfo structure has been modified so that it expects HypervisorInfo
structure instead of the generic PathInfo regarding the information
about the hypervisor.
Fixes #351

cc-env: Add machine type to hypervisor information

---

Makefile
cc-env_test.go
config.go
config/configuration.toml.in
config_test.go

This patch implements config.go in order to switch between different
hypervisor machine types such as pc-lite, pc or q35.
Fixes #350

config: Make hypervisor machine type configurable

---

main.go

Log the full path to the configuration file being used by the runtime
as a debug aide.
Fixes #357.

logging: Add path to config file

---

Makefile
cc-env_test.go
config.go
config/configuration.toml.in
config_test.go

Allow 9pfs to be used instead of block device for devicemapper.
virtcontainers uses this configuration to use 9pfs
instead of block device.
Fixes #361

config: Make block device usage configurable

---

Gopkg.lock
delete.go
exec.go
kill.go
oci.go
oci_test.go
state.go
vendor/github.com/containers/virtcontainers/agent.go
vendor/github.com/containers/virtcontainers/api.go
vendor/github.com/containers/virtcontainers/api_test.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/hyperstart.go
vendor/github.com/containers/virtcontainers/hypervisor.go
vendor/github.com/containers/virtcontainers/hypervisor_test.go
vendor/github.com/containers/virtcontainers/noop_agent.go
vendor/github.com/containers/virtcontainers/noop_shim.go
vendor/github.com/containers/virtcontainers/noop_shim_test.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/qemu.go
vendor/github.com/containers/virtcontainers/sshd.go

This PR includes recent changes from virtcontainers. It changes the way `delete` and `kill` commands are implemented and allows `cc-runtime list` to return an accurate result of the container status.
It fixes #376 #377 #378 and #382

Globally improves kill/delete commands

---

Makefile

Build variables will affect configuration file.
Fixes #285
Signed-off-by: WANG Chao <chao.wang@ucloud.cn>

build: configuration file depends on build variables

---

Makefile
cc-env.go
cc-env_test.go
config.go
config/configuration.toml.in
config_test.go

Add support to pass extra kernel parameters in configuration.
The story behind this feature is, I have trouble running centos:6
/bin/bash and it turns out guest kernel is using vsyscall=none which
breaks old libc.
Fixes: #368
Signed-off-by: WANG Chao <chao.wang@ucloud.cn>

config: support kernel parameters

---

Makefile

This patch modifies the default configuration provided through the
Makefile so that our runtime will use "pc" machine type for our
Qemu hypervisor. This change implies that we have to use vmlinuz
which is the compressed kernel expected by the BIOS run by "pc"
machine type.
Fixes #329

qemu: Move from pc-lite to pc machine type

---

create.go
versions.txt

This commit modifies the systemd target to use, so that it will use
cc-agent instead of hyperstart agent.
Fixes #348

runtime: Switch to the new agent

---

docs/release_notes.sh
versions.txt

This patch adds a script to generate release notes.
Usage
./docs/release_notes.sh <start-commit/tag> <New-version>
start-commit/tag is the commit to start to get git changes.
Example:
$./docs/release_notes.sh 3.0.0-alpha.5 3.0.0.beta.1
Fixes #409

docs : Automate release notes

---

docs/developers-clear-containers-install.md

Now that we have moved to use PC instead of PC-lite, we use the
vmlinuz kernel instead of vmlinux to boot a Clear Container. This
commit updates the location where the linux-container file is
downloaded, which now provides the compressed kernel.
Fixes #414.

docs: Update instruction to download compressed kernel

---

docs/fedora-installation-guide.md
docs/ubuntu-installation-guide.md

The installation guides have references to alpha versions
in them. Now, that we will be moving to beta, remove these
references.
Fixes #418

docs: Remove references to alpha version

---

docs/debug-agent.md

This patch adds documentation on how to get
agent debug logs.

Docs: Add how to get agent debug logs.

---

cc-check.go
cc-check_test.go

If running under a hypervisor, the kvm "unrestricted_guest" option is
not required.
Fixes #439.

cc-check: warn if unrestricted_guest unavailable under hypervisor

---

create.go
delete.go
exec.go
kill.go
list.go
main.go
main_test.go
oci.go
pause.go
start.go

Make the virtcontainers implementation switchable for testing.
By default, the official virtcontainers implementation is used, but
switch to the VCMock implementation for testing.
Fixes #449.

tests: switchable virtcontainers implementation

---

main_test.go
utils.go

Add various helper functions to allow the easy creation of
virtcontainers objects and the manipulation of OCI resources:
func newTestCmd() vc.Cmd
func newTestContainerConfig(dir string) vc.ContainerConfig
func newTestHypervisorConfig(dir string, create bool) (vc.HypervisorConfig, error)
func newTestPodConfigNoop(dir string, create bool) (vc.PodConfig, error)
func newTestRuntimeConfig(dir, consolePath string, create bool) (oci.RuntimeConfig, error)
func createOCIConfig(bundleDir string) error
func makeOCIBundle(bundleDir string) error
func readOCIConfigFile(configPath string) (oci.CompatOCISpec, error)
func writeOCIConfigFile(spec oci.CompatOCISpec, configPath string) error
func runCommandFull(args []string, includeStderr bool) (string, error)
Fixes #451.
Signed-off-by: James O. D. Hunt …

tests: Add helper functions

---

state.go

The json displayed with container state command is
not idented. Apply indentaion for readability.
Fixes #445

state: Apply indentation to the state output.

---

config/configuration.toml.in

The comment section for default_vcpus neglected to mention that
settings between 1 and 255 set the actual number of vcpus created
in the VM.
Fixes: #453

config: Add comment about ncpus >0 <=255

---

start_test.go

Use mock framework to implement unit tests for start.go
Fixes #399

tests: Add unit tests for start.go

---

create_test.go
main_test.go

Previously, makeOCIBundle() would create a fresh bundle every time it
was called. However, since it uses docker to generate the rootfs, that
could take a while on slow systems meaning the tests could timeout.
To overcome this issue, the tests now create a full pristine bundle at
startup and makeOCIBundle() now just copies the pristine bundle to the
location requested by the calling test.
This change also removes the requirement that the bundle directory exist
before calling makeOCIBundle().
Fixes #461.

tests: Stop bundle creation timing out tests

---

cc-env.go
list.go
list_test.go
main.go

Increase unit-test coverage on list.go to 98.6%.
Once https://github.com/containers/virtcontainers/pull/355 lands and is
re-vendored into the runtime, coverage will be 100% for this file.
Fixes #404.

tests: Increase unit-test coverage for list.go

---

pause_test.go

Relying on vcMock framework introduced in virtcontainers library,
this commit raises the unit test coverage of pause.go file to 100%.
Fixes #394

pause: Implement full unit test coverage

---

Gopkg.lock
list.go
state.go
vendor/github.com/containers/virtcontainers/pkg/hyperstart/hyperstart.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils_test.go

Shortlog of what have been added since the last vendoring:
ed778ce oci: Remove error return from StatusToOCIState()
3758c22 agent: Make the error message from agent generic.
Fixes #479.

vendor: Update virtcontainers vendoring for updated StatusToOCIState

---

.ci/go-test.sh
.travis.yml

Some of the unit tests require root privileges to run. Conversely, some must
be run as a non-root user.
Modify the unit-tests to run twice, once as a non-root user and again
as the root user, and combine the resulting unit-test coverage files to
get a true unit-test coverage figure.
Fixes #483.

tests: Run unit tests as root and non-root.

---

.ci/go-no-os-exit.sh
exit_test.go

Replace os.Exit() call in exit() with a call to function
variable exitFunc  that is assigned to os.Exit()
In the test assign exitFunc to a test function to help
test exit() with 0 and more atexit functions.
Fixes #402

tests: Add test for exit.go

---

docs/fedora-installation-guide.md

Update the Fedora installation document based on recent feedback from #495:
- Ensure all `dnf` commands are run non-interactively
(and with the `-y` option in the same position in the command-line).
- Ensure the docker service starts on boot.
Fixes #509.

docs: Improve Fedora install doc

---

docs/fedora-installation-guide.md

Adding the user to the docker group using groupadd(8) may not be a good
idea from a security perspective, so continue to use sudo(8) in all docs
to access docker.
Fixes #513.

docs: Remove call to groupadd

---

scripts/release_notes.sh

The Changes section, if left unedited, is pretty much just a copy
of the shortlog. Add a reminder in the auto-generated text that
this section should be edited down to a human readable overview.
Fixes: #517

scripts: relnotes: Add reminder to fixup Changes section

---

scripts/release_notes.sh

When we moved the script to a new directory we broke the relpath
link to the limitations.md file. Fix it.
Fixes: #519

scripts: relnotes: fix path to limitations.md

---

scripts/release_notes.sh

The script had the #!/bin/bash not on the first line, where
it should be. Fix with the obvious line move.
Fixes: #515

scripts: relnotes: fix /bin/bash line

---

docs/developers-clear-containers-install.md

Remove all instructions that are duplicated in the installation guides
and require developers to install via the installation instructions as
a prerequisite.
Also fixup some formatting (headings and indents).
Fixes #511.

docs: Improve developers installation guide

---

Gopkg.lock
vendor/github.com/01org/ciao/.travis.yml
vendor/github.com/01org/ciao/DeveloperQuickStart.md
vendor/github.com/01org/ciao/README.md
vendor/github.com/01org/ciao/packages.json
vendor/github.com/01org/ciao/qemu/qmp.go
vendor/github.com/01org/ciao/qemu/qmp_test.go
vendor/github.com/01org/ciao/ssntp/ssntp.go
vendor/github.com/containers/virtcontainers/Gopkg.lock
vendor/github.com/containers/virtcontainers/capabilities.go
vendor/github.com/containers/virtcontainers/capabilities_test.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/container_test.go
vendor/github.com/containers/virtcontainers/hyperstart.go
vendor/github.com/containers/virtcontainers/hypervisor.go
vendor/github.com/containers/virtcontainers/mock_hypervisor.go
vendor/github.com/containers/virtcontainers/mount.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils_test.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils_test_config.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/qemu.go
vendor/github.com/containers/virtcontainers/qemu_test.go

Virtcontainers update includes support for hotplugging drives,
fix for container hostname and declutter of logs.
Ciao update includes a fix for hot unplugging block devices
for qemu>=2.9
Shortlog for virtcontainers:
fc19dad log: Be less chatty at Info level
aa2cab9 qemu: Typo fix
67b0def oci: Set hostname to the one passed in spec file
559e470 Merge pull request #358 from amshinde/test-for-add-drive
9a190fa tests: Add test for addDrive in container.go
389d979 docs: Create CODE_OF_CONDUCT.md
25bac0d state: Add bool variable to indicate if drive was hotplugged
ee7ac26 hotplug: Hotunplug drive when container is stopped.
4f7150d vendor: Vendor latest ciao package
86bd45f hotplug: Hotplug drive when container is started
91dd21c capabilities: Add a capabilities interface for hypervisor
c1440f9 …

vendor: Update virtcontainers and ciao vendored packages.

---

Makefile

Requesting a system build does not correctly invalidate any previous
build.
Force the correct behaviour by ensuring a non-installation build
depends on "clean". This guarantees the generated code will be
recreated and ensures the correct version details in the resulting
binary.
Fixes #373.

build: Ensure version details correct for system build

---

CONTRIBUTING.md

Potential contributors need to be aware of and agree to the projects
code of conduct before making contributions.
Fixes #535.

docs: Reference the code of conduct doc in the contributing doc

---

docs/centos-installation-guide.md
installation/centos-setup.sh
installation/installation-setup.sh
versions.txt

Write a document explaining how to install Clear Containers 3.0 on a
CentOS 7 system. Added associated scripts and configuration
files (which are lightly modified versions from
https://github.com/01org/cc-oci-runtime).
Fixes #371.

docs: Create CentOS installation guide

---

Makefile
create_test.go
oci.go
oci_test.go

Getting an absolute path while not having a cgroup mount
from the OCI spec is a valid case. In that case the path
should be interpreted as a relative one to the system
cgroup mount point.
Fixes #552

oci: Follow the OCI spec for cgroup paths

---

Gopkg.lock
delete_test.go
exec_test.go
main_test.go
run_test.go
vendor/github.com/01org/ciao/qemu/qemu.go
vendor/github.com/01org/ciao/qemu/qemu_test.go
vendor/github.com/containers/virtcontainers/CODE_OF_CONDUCT.md
vendor/github.com/containers/virtcontainers/Gopkg.lock
vendor/github.com/containers/virtcontainers/README.md
vendor/github.com/containers/virtcontainers/api_test.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/hyperstart.go
vendor/github.com/containers/virtcontainers/hypervisor.go
vendor/github.com/containers/virtcontainers/network.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils_test.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/qemu.go

Update virtcontainers to 1.0 version.
Added support for memory and cpu reservation
Added stroage hotplug support
Added code of conduct
Added memory pre-allocation, realtime and memory locking support
Fixed nested virtualization support
Fixed log verbosity
Fixed pod cleanup
- Fix issues deleting a container after a failing start
e.g: docker run -ti busybox non-exithing binary
Fixes: #507

vendor: virtcontainers 1.0

---

README.md

Although the wiki includes links to the installation guides,
so should the README.
Fixes #537.

docs: Add link to install guides in README

---

main.go

Simplified makeVersionString() to avoid duplicating string literals.
Fixes #554.

main: Avoid duplication in makeVersionString()

---

Makefile
data/completions/bash/cc-runtime
main.go

Add tab completion script for bash(1) to make working with the
runtime "standalone" more comfortable and efficient.
Fixes #562.

scripts: Add bash tab completion script

---

oci_test.go

Update cgroup test
TestProcessCgroupsPathAbsoluteNoCgroupMountDestinationFailure()
to take account of new behaviour resulting from #553).
Fixes #560.

tests: Improve unit-test coverage for oci.go

---

cc-check.go
create.go
kill.go
list.go

golint is now causing builds to fail due to the need to simplify
certain functions that return errors.
Fixes #573.

check: Fix golint errors.

---

Makefile

Honour the DESTDIR variable when installing the bash completion script.
Fixes #566.

build: Install bash completions below DESTDIR

---

Makefile
README.md
config.go
config_test.go
docs/architecture/architecture.md
docs/developers-clear-containers-install.md
installation/centos-setup.sh
main.go
main_test.go
utils.go

Modify the runtime to look in multiple locations for its configuration.
Previously, with a CC system build, the build system would generate (and
the runtime would read) the file below:
/etc/clear-containers/configuration.toml
This file was represented by the DESTCONFIG build variable.
However, now a CC system build will generate the following path instead:
/usr/share/defaults/clear-containers/configuration.toml
But the runtime will look in both locations in the following order
(with build variables in brackets):
/etc/clear-containers/configuration.toml (DESTSYSCONFIG)
/usr/share/defaults/clear-containers/configuration.toml (DESTCONFIG)
(Note that the original configuration file now has a new build variable
name: DESTSYSCONFIG).
The first file the runtime finds will be used. Since …

config: Support a stateless system

---

versions.txt

We are using kernel 4.9.47-77 and clear-containers-image 17270 in the
current build of clear-containers.
Signed-off-by: Geronimo Orozco <geronimo.orozco@intel.com>

versions.txt: Update kernel and image versions

---

Makefile
config.go
config/configuration.toml.in
config_test.go

```enable_prealloc=true```  Will result in the upfront allocation  and locking down of all VM memory, resulting in lower VM density.
```enable_swap=true```   Will enable swap of VM memory, resulting in higher VM density with potentially higher latency
Enabling the two together results in undefined behavior.
```enable_debug=true```   Will enable hypervisor and container kernel logs
Fixes https://github.com/clearcontainers/runtime/issues/568

Configuration: Add support for fine grained control of memory management and debug

---

README.md

This commit replaces old Travis and Semaphore badges with Jenkins
ones.
Fixes #594

readme: Update CI badges

---

Gopkg.lock
create_test.go
main_test.go
run_test.go
vendor/github.com/stretchr/testify/.travis.yml
vendor/github.com/stretchr/testify/assert/assertion_forward.go
vendor/github.com/stretchr/testify/assert/assertions.go
vendor/github.com/stretchr/testify/assert/assertions_test.go
vendor/github.com/stretchr/testify/assert/forward_assertions.go
vendor/github.com/stretchr/testify/assert/http_assertions.go
vendor/github.com/stretchr/testify/assert/http_assertions_test.go

This reverts commit 535be199a4a36cc33f6a3d21bf2415acb39ea4dd, reversing
changes made to 7e2466d826dee60f837ae9c877c1123918f12e0e.
This change broke the Jenkins CI and local unit-test builds (unable to
run them with either go 1.8 or go 1.9).
Fixes #615.

Revert "Merge pull request #587 from mcastelino/topic/govet"

---

.ci/go-test.sh

Increase unit-test timeout to 10 seconds as 5 seconds is often
not enough in a Jenkins environment.
Allow the timeout to be configured by setting the variable
"CC_GO_TEST_TIMEOUT" to any valid value supported by
"go test -timeout X".
Fixes #617.

tests: Increase unit test timeout

---

Makefile

Make the build display the version of Go being used.
Fixes #620.

build: Show version of go

---

Makefile
README.md
cc-env.go
cc-env_test.go
config.go
config_test.go
list.go

Paths need to be resolved as soon as possible to ensure that the
hypervisor is launched with fully-resolved paths.
Fixes #607.

paths: Resolve paths earlier

---

cc-check.go
config.go
exec.go
run.go

Hi, my friends, 
Today I spend some time in learning this project clearcontainers/runtime, and will try to use this in the own company's virtualization environment. 
What is amazing project this is! I found that you guys organized and maintained the project so well.
I would be excited if I could be involved in this project. While when I am learning the project, I found that maybe there is some place where we could improve a bit.
What I did:
1. simplify some codes;
2. use `return fast` to eliminate some `else` block, since I think this will make codes ident less to be more readable.
fixes https://github.com/clearcontainers/runtime/issues/623
Although these are all tiny changes, feel free to tell me if I could make more improvement.

refactor: simplify code to return the fastpath first

---

Makefile

Commit ffe6ccfc9047245c0d6193738b00973f2ee5460c inadvertently removed the
`CONFIG_IN` variable used by the build to generate part of the warning
message in the auto-generated config file.
Re-added to fix it.
Fixes #635.

build: Fix config file warning message

---

cc-check.go
cc-check_test.go

Change "cc-check" so that it always runs all commands before erroring.
Previously, it would fail on first error, but this could mask the real
reason for failure. For example, on a system with nesting and vhost
disabled, "cc-check" would fail with a nesting error. But the nesting
check is not strictly required (#281) whereas vhost definitely is which
lead to confusing results for users.
"cc-check" will now run all tests and display an error message at the end
if any errors were found in the set of tests run.
Fixes #638.

cc-check: Always run all tests

---

README.md

This commit updates the build badges for Ubuntu 16.04 and 17.04
jenkins jobs since their names changed.
It also adds the build badge related to Fedora 26.
Fixes #647

readme: Update build badges

---

create.go
create_test.go
main_test.go
utils.go

fix write /sys/fs/cgroup/cpu/docker/471fb846c4d02703eebe9d3bafdbba3a5975b6c6535492784036298705576457/tasks: no space left on device
because cpuset.mems in the container's cpuset cgroup directory is empty
Fix #642 
Signed-off-by: Ace-Tang <huamin.thm@alibaba-inc.com>

fix write cgroup no space left

---

main_test.go

Change the unit-test setup code to only download the "busybox" docker
image if it doesn't already exist locally. Since the unit-tests are run
twice (once as a non-privileged user and once as `root`), this can speed
up the overall unit-test runtime significantly.
Fixes #653.

tests: Only pull docker test image if not available locally

---

list.go
list_test.go

Show the owner of the container as a UID (user-id) value.
This ensures that "list" always shows the same number of fields.
Fixes #294.

list: Add container owner field

---

Makefile

By default cc-collect-data.sh was installed as
`/usr/bin` when a DESTDIR is an empty directory.
Fixes: #663

makefile: Fix installation scripts

---

logger.go

Change format of time included in log entries to display the timezone
as an offset.
Example of old format:
time="2017-09-28 13:22:58.965483966 +0100 BST"
Example of new format:
time="2017-09-29T13:22:58.965483966+01:00"
Fixes #650.

logger: Display timezone as offset

---

create_test.go
main_test.go

test copyParentCPUSet() under tmpDir instead of using real
cgroups syatem path, make the test always worked whether
cpuset.cpus and cpuset.mems files in cpu cgroups exist or not.
Signed-off-by: Ace-Tang <aceapril@126.com>
please help me check if the patch is properly, thanks.
ping @sameo

tests: switch to test copyParentCPUSet under tmpDir

---

Makefile
config.go
config/configuration.toml.in

Provide an option to disable nesting customization. This is useful
when running on top of KVM, where disabling the customizations
performed when the runtime detects it is running on top of a VM
results in higher performance.
Fixes https://github.com/clearcontainers/runtime/issues/603
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

Configuration: Provide an option to disable nesting customization

---

data/cc-collect-data.sh.in

The "cc-collect-data.sh" script was incorrectly assuming `cc-shim` was
a systemd unit. Fixed to check by identifier for the shim.
Fixes #681.

scripts: Fix shim log checking for data collection script

---

main.go

Override the default golang panic handling by printing a full traceback
(not just for the current goroutine) and coredumping to allow
crash-handling programs like apport to log the details.
Fixes #688.

main: coredump on internal error

---

.ci/run.sh

The run.sh script has docker tests that are already
covered by our testsuite in the tests repository.
This commit removes those tests.
This commit also changes the way the tests are called in
the tests repository to allow execute OpenShift tests if
the OPENSHIFT_CI envar is set to true.
Fixes: #684.

CI: remove tests from run.sh script

---

Gopkg.lock
vendor/github.com/01org/ciao/qemu/qemu.go
vendor/github.com/containers/virtcontainers/Gopkg.lock
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/device.go
vendor/github.com/containers/virtcontainers/device_test.go
vendor/github.com/containers/virtcontainers/filesystem.go
vendor/github.com/containers/virtcontainers/hypervisor.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils_test.go
vendor/github.com/containers/virtcontainers/pod_test.go
vendor/github.com/containers/virtcontainers/qemu.go

update ciao and virtcontainers
fixes #704 
virtcontainer short log:
c286dbb device: Call addDevice after dereferencing pointer receiver.
caefa12 devices: Refactor device handling
95f3ae9 filesystem: Split function to reduce cyclomatic complexity
4640741 filesystem: Custom marshal and unmarshal device interface objects
e0fef66 qemu: add default machine accelerators
cdc77cc qemu: remove newer machine accelerators
c1291fb qemu: support for custom machine accelerators
93014e4 qemu: support custom bios
e1fa974 vendor: update ciao
ciao short log:
96bd26b openstack/block: Remove unused API for getting limits
fb02316 singlevm: Fix storage tests
dd17576 openstack/compute: Remove flavor API
5f764ed ciao-cli: Use workload API for listing workloads
fd08780 ciao-controller: Add API entrypoints for …

vendor: update ciao and virtcontainers

---

README.md
config.go
config/configuration.toml.in
config_test.go
logger_test.go
main.go
main_test.go

Add config options to toggle debug for the shim and the runtime (we already have an option for the hypervisor and the proxy is handled separately).

Make debug configurable

---

oci_test.go

should use t.Skipf() instead of Skip(), or will cause
format error
Fixes #717.
Ace-Tang <aceapril@126.com>
Thank for tell me if the patch is properly

tests: fix format error in TestIsCgroupMounted

---

docs/limitations.md

The latest virtcontainers library supports passing devices
to the VM with VFIO passthrough.
Update limitations to reflect this.
Fixes #713

docs: Update limititations page to mention support for VFIO.

---

oci.go

Improve one of the errors returned by `getExistingContainerInfo()` when
it fails to obtain the container status by including the container ID
in the returned error.
Fixes #735.

oci: Add conatiner ID to error message

---

main_test.go
utils.go

If docker cannot be connected to, display a more informative error
message along with the error output.
Fixes #776.

Improve docker failure message harder

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containers/virtcontainers/Gopkg.lock
vendor/github.com/containers/virtcontainers/Gopkg.toml
vendor/github.com/containers/virtcontainers/README.md
vendor/github.com/containers/virtcontainers/api.go
vendor/github.com/containers/virtcontainers/api_test.go
vendor/github.com/containers/virtcontainers/cc_proxy.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/device.go
vendor/github.com/containers/virtcontainers/device_test.go
vendor/github.com/containers/virtcontainers/hyperstart.go
vendor/github.com/containers/virtcontainers/network.go
vendor/github.com/containers/virtcontainers/pkg/hyperstart/types.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/proxy.go
vendor/github.com/containers/virtcontainers/qemu.go
vendor/github.com/containers/virtcontainers/utils.go
vendor/github.com/vishvananda/netlink/handle_linux.go
vendor/github.com/vishvananda/netlink/handle_test.go
vendor/github.com/vishvananda/netlink/link.go
vendor/github.com/vishvananda/netlink/link_linux.go
vendor/github.com/vishvananda/netlink/link_test.go
vendor/github.com/vishvananda/netlink/nl/nl_linux.go
vendor/github.com/vishvananda/netlink/nl/nl_linux_test.go

Revendor netlink and virtcontainers to switch the default network connection method to use macvtap.
Fixes #708
Fixes #709
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

Networking: Revendor netlink and virtcontainers to support macvtap

---

Gopkg.lock
Gopkg.toml

virtcontainers has already switched to vendoring specific revisions of dependencies.
Switch the runtime to also adopt the same.
This allows an user to do perform
rm -rf vendor
dep ensure
without having to worry about unwanted changes being picked up.
The downside is that the revendoring becomes manual. It also requires that runtime dependency
revisions match that the exact revision used by virtcontainers (which may be a good thing).
Fixes #779
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

Vendoring: Switch to fixed revision vendoring

---

docs/limitations.md
versions.txt

docs: Document docker version for swarm
Docker swarm support currently requires a back-level version of Docker
so add details to the limitations doc.
Fixes #781.

Document docker swarm version

---

logger.go
logger_test.go

The logger was not correctly converting the values to log into strings
prior to quoting leading to garbled log entries for non-string log
fields.
Added new unit test to ensure correct behaviour.
Fixes #786.

logger: Fix logging of non-string types

---

config/configuration.toml.in

runtime doesn't need ```pause_root_path``` variable any more,
because of the pause binary was removed by a previous commit
fixes #793

config: remove pause_root_path from configuration file

---

versions.txt

- Image 
Changes:
version: 18800
```
Changes in package clear-containers-agent (from
1fa147836736824c32a46889d6fb59402d4e58bd-14 to
9adc9d49378aa0a19b85d02c447b3eb1e2b87774-14):
Jose Carlos Venegas Munoz - new agent version 9adc9d
https://download.clearlinux.org/releases/18800/clear/RELEASENOTES
```
- Kernel
New version: https://github.com/clearcontainers/linux/releases/tag/v4.9.60-80.container
Fixes: #797

versions: Update image and kernel

---

cc-env.go
cc-env_test.go

The `getAgentInfo()` can't fail (now), so remove the error return value.
Fixes #791.

cc-env: Remove unused error return value

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containers/virtcontainers/api.go
vendor/github.com/containers/virtcontainers/api_test.go
vendor/github.com/containers/virtcontainers/bridge.go
vendor/github.com/containers/virtcontainers/bridge_test.go
vendor/github.com/containers/virtcontainers/cni.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/device.go
vendor/github.com/containers/virtcontainers/filesystem.go
vendor/github.com/containers/virtcontainers/hyperstart.go
vendor/github.com/containers/virtcontainers/hypervisor.go
vendor/github.com/containers/virtcontainers/hypervisor_test.go
vendor/github.com/containers/virtcontainers/mock_hypervisor.go
vendor/github.com/containers/virtcontainers/mock_hypervisor_test.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/qemu.go
vendor/github.com/containers/virtcontainers/qemu_test.go

this new version of virtcontainers has support for hotplugging
in Qemu Q35
shortlog:
aa2ba14 Remove redundant "if" check
37dc3c6 cni: Assign the netpair for virtual endpoints after scan
8f846a2 cni: Fix bug while updating endpoints after scanning net namespace
eb39def qemu: Provide unique QMP sockets names
6026603 qemu: Don't wait for the end of the VM
eeacf8b qemu: Fix disconnectCh issue and simplify it
711783f agent: hyperstart: Tear down properly the pod
b20ba87 pod: Improve pod create performances
d449ece api: Refactor RunPod()
c3663b2 pod: Run post-start hooks outside netns
42df5a6 hypervisor: add hot plugging support for Qemu Q35
fixes #829

vendor: update virtcontainers

---

versions.txt

This commit adds the components (and their respective version) that
are listed in the clearcontainers/tests/test-versions.txt. After
merging this, we would be able to remove the test-versions.txt
from the tests repository and rely in the versions.txt from this
repository, which will make maintenance easier and less
fragile.
The components added this list are:
- Qemu-lite
- CRI-O
- runc for CRI-O
- kubernetes
- Openshift
- Go version
Fixes: #608.

versions: Add missing components

---

Makefile
config.go
config/configuration.toml.in
config_test.go

default_bridges allows user specify how many PCI bridges
must be included in the VM, this allow to hot plug until
~150 devices
fixes #831

hotplug: add default_bridges to configuration file

---

main.go
ps.go
ps_test.go

ps command is used by ```docker top``` to show
the processes running inside the container
partially fixes #95

cli: implement ps command

---

cc-check.go

The "cc-check" command should only display the KVM success message
if the KVM checks are actually run (if invoked as `root`).
Fixes #850.

cc-check: Only display KVM message if KVM checks run

---

versions.txt

using clear-containers image 19490, CC fails to start pods
in kubernetes.
Fixes #861

versions: downgrade clearcontainers image

---

docs/sles-installation-guide.md
installation/sles-setup.sh

We don't have an installation guide for SuSE although we are producing
packages for it.
This commit adds an installation guide for SLES 12 SP1 and an installation
script.
Fixes #734 
Signed-off-by: Erick Cardona <erick.cardona.ruiz@intel.com>

docs: Add SLES installation guide

---

docs/Passing-Devices-with-Clear-Containers.md

This documentation shows how block and vfio device groups
can be passed to Clear Containers with --device Docker
command option.

docs: Add documentation on how to pass devices with --device.

---

README.md

PR #849 added new features to cc-check but neglected to update the
README to explain that those extra tests are only run when running the
command as the `root` user.
Fixes #853.

doc: Update README for "cc-check"

---

docs/centos-installation-guide.md

SLES documentation was created based on the CentOS document. Some
updates were made to add more clarity to the installation steps. This
commit adds the updates back to the CentOS guide.
Fixes: #864

centos: Update CentOS documentation

---

exec.go

Fix running `docker exec` with the `--user=` option. Previously,
specifying `--user=` with any user (or user and group) would be ignored
and the workload would run as `root` (`UID`+`GID`). This was because the
runtime was setting the user to run the workload from the `Username`
field in the OCI `Process.User` struct. However, that field is
Windows-only so the value was always zero, denoting `root`.
Fixes #867.

exec: Fix "docker exec --user"

---

data/cc-collect-data.sh.in

Add the timezone the script was run in along with `docker versions`
details (since `docker info` doesn't show client information).
Fixes #878.

scripts: Improvements to cc-collect-data script

---

docs/limitations.md

We get warnings in the host dmesg such as:
```
[  319.406575] kvm [2415]: vcpu0 unhandled rdmsr: 0x1c9
[  319.483944] kvm [2415]: vcpu0 unhandled rdmsr: 0x64e
[  319.483966] kvm [2415]: vcpu0 unhandled rdmsr: 0x34
```
that although benign, can understandably perturb users.
Document them so at least information about the warnings
can be found without having to submit a new issue etc.
Fixes: #883
Signed-off-by: Graham whaley <graham.whaley@intel.com>

docs: limitations: document 'unhandled rdmsr' dmesg warnings

---

docs/developers-clear-containers-install.md

Added details on how to reconfigure docker to dev guide, along with a bunch of other minor improvements.

Add docker config to dev guide

---

config.go
config/configuration.toml.in
config_test.go

This commit modifies the config so that we can actually select either
Kata or Clear Containers case through the runtime.
Fixes #903
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

config: Add Kata Containers possibility

---

docs/limitations.md

docs: Fix option name in limitations doc.
Correct Seems that --host=net should be instead by --net=host.
Fixes #899.

docs: Fix option name in limitations doc

---

config.go
config_test.go

`updateRuntimeConfig()` was not setting the agent type, so if the
runtime was configured for kata containers, it would try
to use a hyperstart agent.
Fixes #911.

config: Set agent type

---

docs/architecture/architecture.md

Update the architecture document to reflect the new proxy behaviour
where there is a proxy instance per virtual machine rather than a
single host-level proxy instance.
This should strictly have been handled on #835.
Fixes #908.

docs: Update arch doc for one proxy / VM

---

docs/Using-SRIOV-and-Clear-Containers.md

Most of the documentation has been moved from 2.x with
some cleanup and references to the 3.0 runtime.
Contributions-by: Archana Shinde <archana.m.shinde@intel.com>

docs: Add documentation for SRIOV

---

versions.txt

Image 19790 still has issues for setting up networking inside
a kubernetes pod.
See https://github.com/clearcontainers/agent/issues/182
This commit downgrades the version of the image to 19350, which
is the latest that is known to work flawlessly.
Fixes #889

versions: downgrade clear containers image

---

versions.txt

The CI is now using version 17.12 to test the changes on
the Clear Containers repo and it has been working correctly
for the integration tests.
Fixes: #913.

versions: update supported docker version to 17.12

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containers/virtcontainers/.gitignore
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/device.go
vendor/github.com/containers/virtcontainers/device_test.go
vendor/github.com/containers/virtcontainers/hyperstart_agent.go
vendor/github.com/containers/virtcontainers/hypervisor.go
vendor/github.com/containers/virtcontainers/kata_agent.go
vendor/github.com/containers/virtcontainers/kata_shim.go
vendor/github.com/containers/virtcontainers/mount.go
vendor/github.com/containers/virtcontainers/network.go
vendor/github.com/containers/virtcontainers/network_test.go
vendor/github.com/containers/virtcontainers/pkg/hyperstart/types.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils_test.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/qemu.go
vendor/github.com/containers/virtcontainers/qemu_test.go
vendor/github.com/containers/virtcontainers/shim.go

Update virtcontainers specifically for commit fb1eecd which fixes the
issue of lingering bind-mounts after a container has been killed.
shortlog of virtcontainers changes:
fb1eecd mount: Fix unmount of dangling bind-mounts
d7462c7 pkg/oci: Clarify resource calculation comment
027aab8 qemu: adjust QMP naming to avoid non-unique truncation
0c4064e capabilities: Pass capabilities to hyperstart.
e20ba9d oci: Add support for capabilities
6776dd9 shim: Correct kata debug flag
b307c08 qemu: refactor/simplify addDevice function
747d364 vhost-user: rewrite to use interfaces/embedded types
cc67fb0 vhost-user: enabling for vhost-user network devices
f5587cf device: make a more generic function for hypervisor args
d6f0600 gitignore: Add new shim binary to gitignore list
bf8359f gitignore: Add new …

vendor: Re-vendor virtcontainers

---

.ci/run.sh
.ci/setup.sh

There is no need to setup the CC environment with the
root user.
Also after running the setup, we needed to change the ownership
of the $GOPATH directory back from root. With this change we
will not need to do this anymore.
Fixes #930.

CI: do not call .ci/setup.sh with sudo

---

config.go
config_test.go

VM config resources must be honoured in order to create
the pod config with the right number of vCPUs and Memory,
whithout this patch vCPU and Memory will be always 0.
fixes #925

config: honour VM config resources

---

main.go

In order to merge the virtcontainers OCI package logs with
the rest of the cc-runtime ones.
Fixes #934

main: Set the OCI vc package logger

---

.gitignore
Makefile
cc-check.go
cc-env.go
config/configuration.toml.in
data/collect-data.sh.in
data/completions/bash/runtime.in
main.go

Rework the build system to allow the runtime to be built for either
of the following:
- Clear Containers (`cc-runtime` binary and configuration)
- Kata Containers (`kata-runtime` binary and configuration)
The existing build rules are retained but there are now two new rules:
```
$ make build-kata-system
$ sudo make install-kata-system
```
Two new variables have also been added:
- `KATA_SYSTEM_BUILD`: set to any value to build/install for Kata.
- `SYSTEM_BUILD_TYPE`: build for either Clear Containers (set to `cc`) or
Kata (set to `kata`).
See `make help` for further details.
Note that configuration files are installed to a project-specific
directory, allowing for systems to be installed for both Kata and Clear
Containers.
Finally, the bash completion and collection scripts have been …

build: Allow for kata project build

---

scripts/release_notes.sh

Added the missing distros that have installation guides to the release
script.
Also, sorted the list and separated the developer guide from the other
installation links.
Fixes #939.

scripts: Add missing distros to release script

---

.ci/setup.sh

Change the `checkcommits` config to not require an issue for release
PRs.
Fixes #943.

CI: Don't require an issue for release PRs

---

Makefile
arch/amd64-options.mk

Support building on different architectures. Currently, only `amd64`
(`x86-64`) is supported. To add support for a new architecture, create:
```
arch/$(GOARCH)-options.mk
```
To build for a different architecture to the hosts, specify the `ARCH`
variable. For example:
```
$ make ARCH=... generate-config
```
Fixes #928.

build: Add basic architecture framework

---

docs/Using-SRIOV-and-Clear-Containers.md

Add details on how to use `lspci` to check if your NIC
supports SR-IOV.
Fixes: #917

docs: SR-IOV: Document using lspci to check SR-IOV caps

---

Makefile

Check to see if the build is being run from a git clone (with a `.git/`
directory) before installing the git hooks.
Fixes #949.

build: Only install git hooks in a git clone

---

Makefile

Check that `.git` is actually a directory before attempting to install
git hooks.
Fixes #951.

build: Check ".git" is a directory before hook install

---

Makefile
create.go

Set the name of the systemd(1) unit based on the project being built for.
The unit name is used to construct the kernel command line, and then
used by the guests systemd to launch the agent, but previously only the
clear containers agent was supported.
Fixes #955.

build: Set systemd unit name based on project

---

config/configuration.toml.in

Reworded the hypervisor debug option comments in the config file
template to remove out of date information.
Fixes #953.

config: Clean up hypervisor debug comments

---

Makefile
main.go

Display the project URL in the `--help` output which is fixed,
regardless of which project the Clear Containers runtime is built for.
Fixes #961.

usage: Show project URL in help output

---

config/configuration.toml.in
create.go
create_test.go

Any `kernel_params=` values specified in the config file should take
priority over any in-built defaults (for better or for worse).
Fixes #963.

config: Allow user-specified kernel params to take priority

---

cc-check.go

The `cc-check` command requires the "unrestricted_guest" KVM feature.
This is used as a heuristic to determine if the system is new enough to
run a Clear Container.
Fixes #421.

cc-check: Document "unrestricted_guest" requirement

---

docs/fedora-installation-guide.md
docs/ubuntu-installation-guide.md
installation/centos-setup.sh
installation/sles-setup.sh

We no longer run cc-proxy as a daemon on the host.  Update install
directions to no longer reference a Clear Containers service restart and
removed directions for starting a cc-proxy service.
Fixes: #957
Signed-off-by: Eric Ernst <eric.ernst@intel.com>

docs: remove references to Clear Containers proxy service

---

cc-env.go
cc-env_test.go

Change `CCCapable` in `cc-env` / `kata-env` output to
`ContainerCapable` to make it project agnostic.
Fixes #967.

cc-env: Remove "CC" from output.

---

Makefile
data/collect-data.sh.in

Correct the URL displayed when the user runs
`{cc|kata}-collect-data.sh -h`.
Fixes #971.

scripts: Fix collect script bug URL

---

data/collect-data.sh.in

Don't consider the hypervisor startup log message as a "problem".
Fixes #969.

scripts: Ignore qemu startup message

---

Makefile

Don't use git hooks when running under the CI as it will remove the
crucial `config-generated.go` file, which will cause `go test` to fail.
Fixes #984.

build: Don't install git hooks when running under a CI

---

versions.txt

Update agent to version 867639223bbcd15672626bcd7f58cde2530c0cc5
Changes :
f4fe1d8 network: Revert delete conflicting route
88eb422 CI: Don't require an issue for release PRs
bbd24dc agent: Add support to online vCPUs
ae71318 agent: Fix sync issues with exit code and stdout of a process
16eb82e capabilities: Add support for Linux capabilities
41802c2 agent: add libudev as dependency
ad7c8a5 privileges: Add NoNewPrivileges in the api
4c2b752 devices: Bind mount devices only when /dev is expected to be
d38fb19 dev: Listen to udev events and bind mount these to container's
bd925f1 agent: Make the agent the subreaper of all processes
cf05dda vendor: Update libcontainer vendoring
4dac904 dev: Mount /dev from tmpfs before mount namespace is created
3e12a1b debug: Send errors on the control …

versions: image: Update base os to version 20640

---

.ci/go-static-checks.sh
config.go
console.go
list.go
main_test.go
oci.go
start_test.go

Fix lint errors and add the following golang linters to the static checks tool to avoid
such problems recurring:
- `staticcheck`
- `structcheck`
- `unused`
Fixes #988.

Lint fixes

---

cc-env.go
cc-env_test.go
main.go

Add the host architecture to the output of the `cc-env` command.
Fixes #993.

cc-env: Add architecture to output

---

Gopkg.lock
Gopkg.toml
Makefile
config.go
config/configuration.toml.in
vendor/github.com/containers/virtcontainers/agent.go
vendor/github.com/containers/virtcontainers/api.go
vendor/github.com/containers/virtcontainers/cni.go
vendor/github.com/containers/virtcontainers/cnm.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/device.go
vendor/github.com/containers/virtcontainers/hyperstart_agent.go
vendor/github.com/containers/virtcontainers/kata_agent.go
vendor/github.com/containers/virtcontainers/mount.go
vendor/github.com/containers/virtcontainers/network.go
vendor/github.com/containers/virtcontainers/noop_agent.go
vendor/github.com/containers/virtcontainers/pkg/annotations/dockershim/annotations.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/qemu.go
vendor/github.com/containers/virtcontainers/shim.go

This PR add configuation option to allow change how VM will be connected to container network. 
Allowed options are : `default`,  `bridged` and `macvtap`
default will use the default defined by virt contaienrs.
This PR also updates virtcontainers: 
- It allows to define the InternetworkingModel from runtime.
- Allow to stop a container in state created
- CPU topology supports until 240 CPUs
- New dockershim annotations are supported.
f19bd7a oci: Allow to get InternetworkingModel from config
573dcf0 network: Add NetInterworkingModel methods
6d19f56 network: Endpoint type dictate how the connection needs to be made
037a81a network: define internetworking model at endpoint creation
089119a network: remove unsed function createNetworkEndpoints
254ad2a Merge pull request #591 from …

config: Add option to change internetworking model 

---

Gopkg.lock
Gopkg.toml
delete_test.go
kill.go
kill_test.go
vendor/github.com/containers/virtcontainers/container.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/shim.go

CRI-O assumes that anything related to the container should be able
to be unmounted after the container process returned after a kill.
In our case, we have a strong dependency on what should be done before
CRI-O can actually unmount storage because it is plugged into the VM.
This means we have to translate a kill as a stop when needed. The
condition for that is to detect when someone calling into kill would
actually expect to see the container completely stopped. This case
happens for SIGKILL and SIGTERM, and those are the conditions for
our runtime to consider stopping the container after it has been
signalled.
Fixes #1002
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

kill: Fix CRI-O race condition

---

cc-check.go
cc-check_amd64.go
cc-check_amd64_test.go
cc-check_data_amd64_test.go
cc-check_test.go
cc-env.go

Reworked the `cc-check` command to make it easier to support other
architectures.
Fixes #992.

cc-check: Isolate architecture specific code

---

versions.txt

This commit updates the supported versions:
Openshift from v3.6.0 to v3.7.1
Kubernetes from v1.8.3 to v1.9.2
CRI-O from v1.0.4 to v1.9.0

versions: Update Openshift, Kubernetes and CRI-O

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containers/virtcontainers/kata_agent.go
vendor/github.com/containers/virtcontainers/shim.go
vendor/github.com/intel/govmm/qemu/qemu.go
vendor/github.com/intel/govmm/qemu/qmp.go

Re-vendor virtcontainers to bring latest changes in govmm for machine
option.
13d23e2 vendor: Re-vendor govmm
a43389e (origin/kata_crio_overlay) kata_agent: Ignore resources from the specification
1479051 kata_agent: Empty namespaces paths
a28064c kata_agent: Fix 9pfs rootfs
97be8e1 (origin/update_dep_vendoring) vendor: Update Gopkg.toml for new prune syntax
a0ee7ef vendor: Remove constraints from packages not directly vendored
195d71f Run cc-shim in the network namespace of pod
Fixes #1012

vendor: Re-vendor virtcontainers to include changes in govmm.

---

logger.go
logger_test.go

PR #790 (specifically commit f98e61976904b8972b15345dc26cc38833104ffa)
regressed the logger by dropping the nanosecond timestamps that we used
to have in the global log.
Re-introduce nanosecond timestamps and add a new unit test to avoid
this re-regressing.
Fixes #1014.

logger: Fix nanosecond timestamps

---

Gopkg.lock
Gopkg.toml
vendor/github.com/containers/virtcontainers/api.go
vendor/github.com/containers/virtcontainers/bridge.go
vendor/github.com/containers/virtcontainers/hyperstart_agent.go
vendor/github.com/containers/virtcontainers/hypervisor.go
vendor/github.com/containers/virtcontainers/mock_hypervisor.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/qemu.go
vendor/github.com/containers/virtcontainers/qemu_amd64.go
vendor/github.com/containers/virtcontainers/qemu_arch_base.go
vendor/github.com/containers/virtcontainers/qemu_arm64.go
vendor/github.com/containers/virtcontainers/shim.go

This will add ARM support into the runtime.
5236b92 documentation: Add API usage example
77c41ca documentation: Add short container 1.0 API description
0fbae82 documentation: Add short pod 1.0 API description
5a2d207 documentation: Document the 1.0 API
1ccb3a4  pod: Fetch pod network only from createPod()
563c175 qemu: change function names
d8a6dd3 qemu: update qemu init
b877182 qemu: add support for ARM
485b51b hypervisor: remove getState function
Fixes #1019

vendor: Re-vendor virtcontainers to bring ARM support.

---

logger_test.go

`TestNewSystemLogHook()` checks to ensure a nanonsecond timestamp is
generated. However, the `time.RFC3339Nano` time format truncates
trailing zeros meaning a nanosecond timestamp won't always have nine
digits.
Fixes #1017.

logger: Fix nanosecond timestamp test

---

config/configuration.toml.in

In case a container's rootfs is backed by a block device,
this flag prevents the block device from being used directly
by the hypervisor.

config: Add comments for the DisableBlockDeviceUse flag

---

main.go

Since the runtime is called multiple times by the container manager, add
the command-line sub-command name to all log entries to make it clear
which command was running when a particular log message was produced.
Note that CLI arguments are already logged once at runtime startup. This
change is more useful for the scenarios where only a log excerpt is
available (for example when running `cc-collect-data.sh` which only
extracts error logs).
Fixes #1024.

logging: Add CLI command to logs

---

versions.txt

This version of agent has support for SCSI.
Fixes #1026

versions: Update agent version to pull in SCSI support

---

main.go

logging: Add name to all log calls
Fixed a bug whereby PR #1025 created a `name` variable that masked the
main variable of the same name (containing the program name). Changed
the logic slightly so that all log entries now include the program name.
logging: Add PID field to logs
Add process ID to log entries.
Fixes #1030.

Logging fixes

---

docs/fedora-installation-guide.md

Update the versions of Fedora that are supported by Clear
Containers 3.0 to Fedora 26 and 27. These are the only Fedora
versions currently available in OpenSUSE OBS repo
(http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/)
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

fedora-installation-guide: update Fedora versions supported

---

config.go
config/configuration.toml.in
config_test.go

the maximum number of vCPUs per VM shouldn't not exceed
the number of physical cores, otherwise we could face issues
with KVM and other architectures
fixes #1028

config: don't exceed the number of physical cores

---

config/configuration.toml.in
docs/cpu-constraints.md
docs/limitations.md

In order to have a fast boot time and small memory foot print,
this patch changes the default number of vCPUs to 1.
Other benefit of these change is the control over almost all the vCPUs,
all vCPUs less one will be hot pluggable.
fixes #1032

config: set 1 vCPU as the default number of vCPUs

---

config.go
fatal.go
main.go

If the runtime detects an internal error or if it receives
a fatal signal, write a stack trace to the log and exit.
If debug is enabled also dump core.
Note: This replaces the previous `debug.SetTraceback()` call which
logs to `stderr`, which is not desirable.
Fixes #1053.

main: stacktrace/coredump on error

---

Gopkg.lock
Gopkg.toml
config.go
config_test.go
vendor/github.com/containers/virtcontainers/hypervisor.go
vendor/github.com/containers/virtcontainers/pkg/oci/utils.go
vendor/github.com/containers/virtcontainers/pod.go
vendor/github.com/containers/virtcontainers/qemu.go

VMConfig.VCPUs is no more part of the virtcontainer API.
virtcontainer starts the VM with the number of vCPUs specified
by DefaulVCPUs (default_vcpus).
fixes #1047

config: Don't use VMConfig.VCPUs

---

data/collect-data.sh.in

Add the agent version to the collect script output.
Fixes #1055.

scripts: Add agent version to collect script

---

.ci/go-static-checks.sh
Makefile

Add two additional linters, `varcheck` and `unconvert`, that check for
unused globals and unnecessary conversions respectively.
Fixes #1066.

CI: Add varcheck and unconvert linters

---

versions.txt

Update versions we use for testing:
CRI-O from v1.9.0 to v1.9.7
Kubernetes from v1.9.2 to v1.9.3
runc from v1.0.0-rc4 to v1.0.0-rc5
Fixes #945.

versions: update CRI-O, kubernetes and runc

---

Gopkg.lock
Gopkg.toml
vendor/github.com/dlespiau/covertool/pkg/cover/cover.go

Re-vendor covertool to work with golang 1.10.
Changes:
5072b09 CI: Update travis for go1.10
7cf24e2 cover: Fix build for 1.10
d45792f command; Factor out a WriteProfilesToFile function
012b32c profile: Factor out WriteProfiles to its own file
a61bda3 merge: Rename WriteProfile to WriteProfiles for consitency
449c650 merge: Remove unused type
77573e5 merge: Remove spurious 'profile' in help text
e0e4815 travis: Add go 1.9 to the test matrix
df49b48 README: Add a new covertool section and more context for instrumented binaries
a89ec05 examples: Fix an "instrumented" typo
Fixes #1072.

vendor: Update covertool for go1.10

---

.ci/go-static-checks.sh
exec.go

Run the `maligned` linter to minimise struct space.
Includes the single fix required to pass the `maligned` tests.
Fixes #1064.

CI: Add maligned linter

---

main.go

For consistency with all other timestamps, change `cc-check` to use
nanosecond timestamps when `stderr` is not a terminal.
Fixes #1074.

cc-check: Use nanosecond timestamps when stderr is redirected

---

.ci/setup.sh
.ci/update-vendoring.sh

Add update vendoring script in the CI which will
allows to vendor kata-runtime.
Fixes #1070

ci: Add update vendoring script.

---

versions.txt

Now that we use 'manage_network_ns_lifecycle = true',
we can move on and test with latest CRI-O version.
Fixes: #1081.

versions: update CRI-O version to v1.9.10

---

versions.txt

Clear Containers CI uses go 1.9.4
Fixes: #1085

versions: Update recommended golang version.
